server:
  port: 9000
spring:
  application:
    name: running-information-analysis-service
  datasource:
    url: jdbc:mysql://localhost:3306/running_information
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update